import type { RouteResponse } from "../types/api";
import { formatDistance, formatDuration } from "../utils/format";

interface ComparisonTableProps {
  dijkstra: RouteResponse | null;
  astar: RouteResponse | null;
  quantumRoute: RouteResponse | null;
  quantumRuntimeMs: number | null;
}

interface Row {
  label: string;
  route: RouteResponse | null;
  runtimeOverride?: number;
  accent: string;
}

export default function ComparisonTable({ dijkstra, astar, quantumRoute, quantumRuntimeMs }: ComparisonTableProps) {
  const rows: Row[] = [
    { label: "Dijkstra", route: dijkstra, accent: "#f5a623" },
    { label: "A*", route: astar, accent: "#8b7cf6" },
    { label: "QuantumRoute", route: quantumRoute, runtimeOverride: quantumRuntimeMs ?? undefined, accent: "#2dd4bf" },
  ];

  const costs = rows.map((r) => r.route?.total_cost).filter((c): c is number => c !== undefined && isFinite(c));
  const bestCost = costs.length ? Math.min(...costs) : null;

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="text-left text-[var(--qr-text-muted)] text-xs uppercase tracking-wide border-b border-[var(--qr-border)]">
            <th className="py-2 pr-3 font-normal">Algorithm</th>
            <th className="py-2 pr-3 font-normal">Distance</th>
            <th className="py-2 pr-3 font-normal">ETA</th>
            <th className="py-2 pr-3 font-normal">Cost score</th>
            <th className="py-2 pr-3 font-normal">Runtime</th>
          </tr>
        </thead>
        <tbody className="font-mono-qr">
          {rows.map((row) => {
            const isBest = row.route && bestCost !== null && Math.abs(row.route.total_cost - bestCost) < 1e-9;
            return (
              <tr key={row.label} className="border-b border-[var(--qr-border)]/50">
                <td className="py-2 pr-3">
                  <span className="inline-flex items-center gap-2 font-sans">
                    <span className="h-2 w-2 rounded-full" style={{ backgroundColor: row.accent }} />
                    {row.label}
                  </span>
                </td>
                <td className="py-2 pr-3">{row.route ? formatDistance(row.route.total_distance_m) : "—"}</td>
                <td className="py-2 pr-3">{row.route ? formatDuration(row.route.total_travel_time_sec) : "—"}</td>
                <td className={`py-2 pr-3 ${isBest ? "text-[var(--qr-cyan)]" : ""}`}>
                  {row.route ? row.route.total_cost.toFixed(4) : "—"}
                  {isBest ? " *" : ""}
                </td>
                <td className="py-2 pr-3">
                  {(row.runtimeOverride ?? row.route?.computation_time_ms)?.toFixed(2) ?? "—"} ms
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
      <p className="text-xs text-[var(--qr-text-muted)] mt-2">
        * lowest cost score among the three. QuantumRoute selects among candidate routes generated by
        Yen's algorithm, so it can tie but not beat Dijkstra's optimal cost on cost alone — see the
        Optimization Details panel for what it actually contributes.
      </p>
    </div>
  );
}
