from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class TrafficSimulateRequest(BaseModel):
    scenario: str = Field("low", description="one of: low, medium, heavy, peak, incident, closure")
    seed: int = 42


class TrafficSummary(BaseModel):
    scenario: str
    seed: int
    num_edges: int
    avg_congestion: float
    avg_speed_kmh: float
    num_incidents: int
    num_closures: int
    is_synthetic: bool = True
    disclaimer: str = (
        "Traffic data is generated by a deterministic synthetic simulator "
        "for demo purposes, not a live traffic feed."
    )


class TrafficPredictRequest(BaseModel):
    hour: int = Field(..., ge=0, le=23)
    day_of_week: int = Field(..., ge=0, le=6)
    road_length_m: float = Field(150.0, gt=0)
    road_type: str = Field("residential", description="residential, tertiary, secondary, primary")
    lane_count: float = Field(1.0, ge=1)
    speed_limit_kmh: float = Field(30.0, gt=0)
    vehicle_count: int = Field(10, ge=0)
    occupancy: float = Field(0.3, ge=0, le=1)
    incident_flag: bool = False
    intersection_density: float = Field(1.0, ge=0)


class TrafficPredictResponse(BaseModel):
    predicted_speed_ratio: float
    predicted_congestion_level: float
    inference_time_ms: float
    model_loaded: bool
    model_disclaimer: str = (
        "Prediction from a LightGBM model trained on synthetic data. "
        "If model_loaded is false, no trained model was found and a "
        "neutral placeholder value is returned instead of a fabricated one."
    )
